// generated by scripts/model-assets.mjs from ml/results/backtest. do not
// edit by hand: npm run build rewrites it from the csvs the backtest wrote,
// so a retrain that changes the numbers changes this file in the same commit.
import type { BacktestRow } from "./model";

// the test block only, outcomes realized 2022Q1 or later, scored once
export const BACKTEST: BacktestRow[] = [
  { model: "gbm", horizon: 1, maePct: 1.8555, coverage: 0.7659, width: 0.0523, n: 7378 },
  { model: "gbm", horizon: 2, maePct: 2.7484, coverage: 0.8321, width: 0.0844, n: 7378 },
  { model: "gbm", horizon: 4, maePct: 4.4902, coverage: 0.9049, width: 0.1635, n: 7378 },
  { model: "gbm", horizon: 8, maePct: 10.2452, coverage: 0.7253, width: 0.2219, n: 7378 },
  { model: "metro_mean", horizon: 1, maePct: 2.0246, coverage: 0.8777, width: 0.0843, n: 7378 },
  { model: "metro_mean", horizon: 2, maePct: 2.9037, coverage: 0.9179, width: 0.1491, n: 7378 },
  { model: "metro_mean", horizon: 4, maePct: 5.1304, coverage: 0.8676, width: 0.2359, n: 7378 },
  { model: "metro_mean", horizon: 8, maePct: 11.8202, coverage: 0.6857, width: 0.3241, n: 7378 },
  { model: "momentum", horizon: 1, maePct: 2.1019, coverage: 0.7559, width: 0.0589, n: 7378 },
  { model: "momentum", horizon: 2, maePct: 2.9438, coverage: 0.8348, width: 0.1008, n: 7378 },
  { model: "momentum", horizon: 4, maePct: 5.8859, coverage: 0.8131, width: 0.1822, n: 7378 },
  { model: "momentum", horizon: 8, maePct: 15.5581, coverage: 0.54, width: 0.2393, n: 7378 },
  { model: "no_change", horizon: 1, maePct: 2.3043, coverage: 0.8672, width: 0.079, n: 7378 },
  { model: "no_change", horizon: 2, maePct: 3.7164, coverage: 0.912, width: 0.1359, n: 7378 },
  { model: "no_change", horizon: 4, maePct: 7.6606, coverage: 0.8628, width: 0.2012, n: 7378 },
  { model: "no_change", horizon: 8, maePct: 18.0543, coverage: 0.678, width: 0.251, n: 7378 },
  { model: "ridge", horizon: 1, maePct: 1.8184, coverage: 0.76, width: 0.0517, n: 7378 },
  { model: "ridge", horizon: 2, maePct: 2.4722, coverage: 0.8788, width: 0.0979, n: 7378 },
  { model: "ridge", horizon: 4, maePct: 4.4739, coverage: 0.8561, width: 0.1588, n: 7378 },
  { model: "ridge", horizon: 8, maePct: 10.4087, coverage: 0.6427, width: 0.1961, n: 7378 },
  { model: "seqgru", horizon: 1, maePct: 1.9278, coverage: 0.8035, width: 0.0627, n: 7378 },
  { model: "seqgru", horizon: 2, maePct: 2.5655, coverage: 0.8819, width: 0.1013, n: 7378 },
  { model: "seqgru", horizon: 4, maePct: 4.2027, coverage: 0.8746, width: 0.1674, n: 7378 },
  { model: "seqgru", horizon: 8, maePct: 10.1351, coverage: 0.6616, width: 0.207, n: 7378 },
  { model: "windowmlp", horizon: 1, maePct: 2.1839, coverage: 0.8241, width: 0.0726, n: 7378 },
  { model: "windowmlp", horizon: 2, maePct: 3.3935, coverage: 0.9141, width: 0.1318, n: 7378 },
  { model: "windowmlp", horizon: 4, maePct: 6.5756, coverage: 0.9169, width: 0.2421, n: 7378 },
  { model: "windowmlp", horizon: 8, maePct: 15.2849, coverage: 0.6865, width: 0.3439, n: 7378 },
];
