// generated by scripts/model-assets.mjs from ml/results/backtest. do not
// edit by hand: npm run build rewrites it from the csvs the backtest wrote,
// so a retrain that changes the numbers changes this file in the same commit.
import type { BacktestRow, RawBand, TrainingFacts, ForecastFacts, PanelFacts, PanelCoverage, PairedRow, AdmissionRow, WalkRow, WalkBand, WalkPairedRow } from "./model";

// the test block only, outcomes realized 2022Q1 or later, scored once
export const BACKTEST: BacktestRow[] = [
  { model: "gbm", horizon: 1, maePct: 1.9798129593044367, coverage: 0.7934399566278124, width: 0.05924516555967928, n: 7378 },
  { model: "gbm", horizon: 2, maePct: 2.8794963362233457, coverage: 0.8319327731092437, width: 0.0926025451780958, n: 7378 },
  { model: "gbm", horizon: 4, maePct: 5.045249286377029, coverage: 0.8605313092979127, width: 0.157816948419914, n: 7378 },
  { model: "gbm", horizon: 8, maePct: 13.066639676154786, coverage: 0.698292220113852, width: 0.23285463538902113, n: 7378 },
  { model: "metro_mean", horizon: 1, maePct: 2.02464502451641, coverage: 0.877744646245595, width: 0.08426490566460203, n: 7378 },
  { model: "metro_mean", horizon: 2, maePct: 2.9037272617707184, coverage: 0.917863919761453, width: 0.1491336260948901, n: 7378 },
  { model: "metro_mean", horizon: 4, maePct: 5.130428219508361, coverage: 0.8675792897804283, width: 0.23593019348690983, n: 7378 },
  { model: "metro_mean", horizon: 8, maePct: 11.820198549976126, coverage: 0.6856871780970453, width: 0.3240752720214804, n: 7378 },
  { model: "momentum", horizon: 1, maePct: 2.101910686976233, coverage: 0.7558959067497967, width: 0.05891220299929865, n: 7378 },
  { model: "momentum", horizon: 2, maePct: 2.943806163246689, coverage: 0.8347790729194904, width: 0.10075445477300624, n: 7378 },
  { model: "momentum", horizon: 4, maePct: 5.885882509513564, coverage: 0.8130929791271347, width: 0.18218520759462437, n: 7378 },
  { model: "momentum", horizon: 8, maePct: 15.55812160781137, coverage: 0.5399837354296557, width: 0.23927358771520793, n: 7378 },
  { model: "no_change", horizon: 1, maePct: 2.3043222589226358, coverage: 0.8671726755218216, width: 0.07896099305750558, n: 7378 },
  { model: "no_change", horizon: 2, maePct: 3.716367246008759, coverage: 0.9120357820547574, width: 0.13585860115768428, n: 7378 },
  { model: "no_change", horizon: 4, maePct: 7.660592997025248, coverage: 0.8628354567633505, width: 0.20120337195961893, n: 7378 },
  { model: "no_change", horizon: 8, maePct: 18.05434556678832, coverage: 0.6779615071835186, width: 0.2509667382984162, n: 7378 },
  { model: "ridge", horizon: 1, maePct: 1.8753931268975044, coverage: 0.813228517213337, width: 0.06165737468019703, n: 7378 },
  { model: "ridge", horizon: 2, maePct: 2.539255509351907, coverage: 0.8971265925725129, width: 0.1068884751140937, n: 7378 },
  { model: "ridge", horizon: 4, maePct: 4.501441164773867, coverage: 0.8621577663323394, width: 0.1702529871414318, n: 7378 },
  { model: "ridge", horizon: 8, maePct: 10.543415812677054, coverage: 0.6321496340471673, width: 0.19768877169679389, n: 7378 },
  { model: "seqgru", horizon: 1, maePct: 1.9602530573706352, coverage: 0.8297641637300082, width: 0.06799714248742293, n: 7378 },
  { model: "seqgru", horizon: 2, maePct: 2.671279453262647, coverage: 0.9049878015722418, width: 0.11470565617899442, n: 7378 },
  { model: "seqgru", horizon: 4, maePct: 4.534634901141644, coverage: 0.8662239089184061, width: 0.18241369790897707, n: 7378 },
  { model: "seqgru", horizon: 8, maePct: 10.747277911560744, coverage: 0.6420439143399295, width: 0.21333480981100572, n: 7378 },
  { model: "windowmlp", horizon: 1, maePct: 2.249289754468098, coverage: 0.8549742477636216, width: 0.08120229890656891, n: 7378 },
  { model: "windowmlp", horizon: 2, maePct: 3.4767002464936563, coverage: 0.9430740037950665, width: 0.15006127367356595, n: 7378 },
  { model: "windowmlp", horizon: 4, maePct: 7.108772560744736, coverage: 0.9174573055028463, width: 0.26795602022342263, n: 7378 },
  { model: "windowmlp", horizon: 8, maePct: 16.207366610656535, coverage: 0.6949037679587964, width: 0.3811384458599754, n: 7378 },
];

// what the shipped model reads: a sequence over the window, a value at the
// origin, and the columns the panel carries that no model touches
export const INPUTS = { sequence: 7, annual: 4, context: 10 };

// the shipped model's raw 10 to 90 band on the test block, before the margin
export const RAW_BAND: RawBand[] = [
  { horizon: 1, coverage: 0.5898617511520737 },
  { horizon: 2, coverage: 0.623475196530225 },
  { horizon: 4, coverage: 0.669693683925183 },
  { horizon: 8, coverage: 0.580238547031716 },
];

// the two networks' training histories: where validation loss was lowest
export const TRAINING: TrainingFacts[] = [
  { model: "windowmlp", stop: 1, last: 6, flatFrom: null, trainFalls: true },
  { model: "seqgru", stop: 8, last: 13, flatFrom: 3, trainFalls: false },
];

// the shipped forecast as ml/results/forecast/forecasts.csv has it
export const FORECAST: ForecastFacts = {"origin":"2026Q2","end":"2028Q2","far":8,"count":410,"p10":1.6459839866196502,"median":3.7011664794451615,"p90":5.707723263840914,"lowest":-0.7993253227299824,"highest":8.637333739350828,"falling":5,"peak":{"from":2.6607830000329815,"to":2.9753383021023416,"count":35},"fans":[{"cbsa":"16984","median":13.229238317728086,"lo":-5.623649770569039,"hi":39.00626698772201},{"cbsa":"12420","median":1.5250142017174229,"lo":-15.421607013572125,"hi":22.906463020347047}]};

// the panel the model is fitted on, from ml/results/panel_manifest.json
export const PANEL: PanelFacts = {"rows":71072,"metros":410,"first":"1975Q1","last":"2026Q2"};

// the calibration samples the shipped model's band was set on, at every horizon
export const CALIBRATION_N: number | null = 6560;

// the shipped model against every other scored model, a paired test per
// horizon over the test block's origins. difference is the shipped model's
// mean error less the other's, in points, so a negative one has it closer
export const PAIRED: PairedRow[] = [
  { against: "gbm", horizon: 1, origins: 18, difference: -0.019760477554185127, pValue: 0.9151250811330677 },
  { against: "gbm", horizon: 2, origins: 18, difference: -0.2086140030776883, pValue: 0.6274597364179442 },
  { against: "gbm", horizon: 4, origins: 18, difference: -0.5108220063824063, pValue: 0.6779086903501467 },
  { against: "gbm", horizon: 8, origins: 18, difference: -2.3186103619586143, pValue: 0.5956711041964486 },
  { against: "metro_mean", horizon: 1, origins: 18, difference: -0.06420931583565381, pValue: 0.5482519462550728 },
  { against: "metro_mean", horizon: 2, origins: 18, difference: -0.23214731623783058, pValue: 0.5392168647937307 },
  { against: "metro_mean", horizon: 4, origins: 18, difference: -0.5960359842943271, pValue: 0.4833673029252545 },
  { against: "metro_mean", horizon: 8, origins: 18, difference: -1.0728863798658885, pValue: 0.5551091023880084 },
  { against: "momentum", horizon: 1, origins: 18, difference: -0.14185893843950476, pValue: 0.35213100722896923 },
  { against: "momentum", horizon: 2, origins: 18, difference: -0.273058036739805, pValue: 0.4898983259588031 },
  { against: "momentum", horizon: 4, origins: 18, difference: -1.351643433837311, pValue: 0.2912320344352449 },
  { against: "momentum", horizon: 8, origins: 18, difference: -4.810065191643104, pValue: 0.2986589303911128 },
  { against: "no_change", horizon: 1, origins: 18, difference: -0.34373340871529146, pValue: 0.0914129852255687 },
  { against: "no_change", horizon: 2, origins: 18, difference: -1.0447280813799926, pValue: 0.09457654350270026 },
  { against: "no_change", horizon: 4, origins: 18, difference: -3.1263305572179108, pValue: 0.01705463585015081 },
  { against: "no_change", horizon: 8, origins: 18, difference: -7.307164519218375, pValue: 0.018389150767575323 },
  { against: "ridge", horizon: 1, origins: 18, difference: 0.08462846747669472, pValue: 0.3973231932773714 },
  { against: "ridge", horizon: 2, origins: 18, difference: 0.1319453661081431, pValue: 0.13250946376373357 },
  { against: "ridge", horizon: 4, origins: 18, difference: 0.03317667665589324, pValue: 0.9433425127266017 },
  { against: "ridge", horizon: 8, origins: 18, difference: 0.20418220753878916, pValue: 0.7171296654783378 },
  { against: "windowmlp", horizon: 1, origins: 18, difference: -0.2888573889337491, pValue: 0.007513137752657504 },
  { against: "windowmlp", horizon: 2, origins: 18, difference: -0.8050191880462567, pValue: 0.018546047161211887 },
  { against: "windowmlp", horizon: 4, origins: 18, difference: -2.5735086288376636, pValue: 0.06003899936109775 },
  { against: "windowmlp", horizon: 8, origins: 18, difference: -5.459755761919118, pValue: 0.14432652414567565 },
];

// the admission run's validation loss by arm and seed, as ml/admit.py wrote it
export const ADMISSION: AdmissionRow[] = [
  { arm: "nine, what the shipped gate could see", seed: 20260915, loss: 0.01337 },
  { arm: "nine, what the shipped gate could see", seed: 20260916, loss: 0.013552 },
  { arm: "nine, what the shipped gate could see", seed: 20260917, loss: 0.013433 },
  { arm: "nine, what the shipped gate could see", seed: 20260918, loss: 0.013404 },
  { arm: "nine, what the shipped gate could see", seed: 20260919, loss: 0.013502 },
  { arm: "thirteen, plus rents listings permits income", seed: 20260915, loss: 0.013174 },
  { arm: "thirteen, plus rents listings permits income", seed: 20260916, loss: 0.013355 },
  { arm: "thirteen, plus rents listings permits income", seed: 20260917, loss: 0.013255 },
  { arm: "thirteen, plus rents listings permits income", seed: 20260918, loss: 0.013204 },
  { arm: "thirteen, plus rents listings permits income", seed: 20260919, loss: 0.013261 },
  { arm: "fourteen, the set shipped before 2026-09-18", seed: 20260915, loss: 0.013156 },
  { arm: "fourteen, the set shipped before 2026-09-18", seed: 20260916, loss: 0.013183 },
  { arm: "fourteen, the set shipped before 2026-09-18", seed: 20260917, loss: 0.013255 },
  { arm: "fourteen, the set shipped before 2026-09-18", seed: 20260918, loss: 0.0132 },
  { arm: "fourteen, the set shipped before 2026-09-18", seed: 20260919, loss: 0.013187 },
  { arm: "eleven, without zori and listings", seed: 20260915, loss: 0.013195 },
  { arm: "eleven, without zori and listings", seed: 20260916, loss: 0.01345 },
  { arm: "eleven, without zori and listings", seed: 20260917, loss: 0.013297 },
  { arm: "eleven, without zori and listings", seed: 20260918, loss: 0.013261 },
  { arm: "eleven, without zori and listings", seed: 20260919, loss: 0.013183 },
  { arm: "eleven, without permits and income", seed: 20260915, loss: 0.013274 },
  { arm: "eleven, without permits and income", seed: 20260916, loss: 0.013307 },
  { arm: "eleven, without permits and income", seed: 20260917, loss: 0.013364 },
  { arm: "eleven, without permits and income", seed: 20260918, loss: 0.013344 },
  { arm: "eleven, without permits and income", seed: 20260919, loss: 0.013418 },
];

// the yearly refit record, every model fed fhfa's index as each release
// first printed it. span is the first outcome quarter scored: every model
// over the whole record, and over 2022 onward only the shipped model, both
// its bands, and no change
export const WALKFORWARD: WalkRow[] = [
  { model: "ensemble", horizon: 1, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 1.6185099082509786, coverage: 0.8699956952216961, width: 0.06992706834006379, intervalScore: 0.1073982470044205 },
  { model: "ensemble", horizon: 2, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 2.4037439799693487, coverage: 0.8421581288563639, width: 0.12273224817852375, intervalScore: 0.20199443642636636 },
  { model: "ensemble", horizon: 4, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 4.40082341231588, coverage: 0.8023389295451284, width: 0.2997042293280915, intervalScore: 0.50883545054883 },
  { model: "ensemble", horizon: 8, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 8.092965171814964, coverage: 0.7204763954656335, width: 0.43371603149517035, intervalScore: 0.8962068750640655 },
  { model: "gbm", horizon: 1, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 1.5984824820693644, coverage: 0.8915195867412828, width: 0.07304306362503234, intervalScore: 0.0953065361715625 },
  { model: "gbm", horizon: 2, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 2.3558555878423113, coverage: 0.8631797962404936, width: 0.11339111352544227, intervalScore: 0.1685190008709063 },
  { model: "gbm", horizon: 4, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 4.191507722278619, coverage: 0.8224278949634094, width: 0.26121116241760506, intervalScore: 0.3721332293792424 },
  { model: "gbm", horizon: 8, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 8.115494287032675, coverage: 0.7479552303056393, width: 0.4462188708311868, intervalScore: 0.7920456847734183 },
  { model: "metro_mean", horizon: 1, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 1.820302762563098, coverage: 0.860812168173339, width: 0.08349309452622086, intervalScore: 0.1329265588215313 },
  { model: "metro_mean", horizon: 2, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 2.8060916787901844, coverage: 0.8341942889941169, width: 0.16315646043671117, intervalScore: 0.26465642372834897 },
  { model: "metro_mean", horizon: 4, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 4.700356273951473, coverage: 0.7772994690773425, width: 0.30736594574464043, intervalScore: 0.600029186151667 },
  { model: "metro_mean", horizon: 8, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 9.30240896392469, coverage: 0.6902712010331468, width: 0.5672771864848382, intervalScore: 1.1239697937183566 },
  { model: "momentum", horizon: 1, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 1.7615667755726006, coverage: 0.8475391017362606, width: 0.06589212213663784, intervalScore: 0.11329726144571581 },
  { model: "momentum", horizon: 2, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 2.68088376335621, coverage: 0.8440235327880614, width: 0.1387399648919746, intervalScore: 0.22500393728381662 },
  { model: "momentum", horizon: 4, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 5.107486595519075, coverage: 0.7787343951786483, width: 0.1703500257275211, intervalScore: 0.36941513546285926 },
  { model: "momentum", horizon: 8, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 11.459695375784888, coverage: 0.7166738412971732, width: 0.326640413923643, intervalScore: 0.7926248846882369 },
  { model: "no_change", horizon: 1, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 2.2527086060019865, coverage: 0.8523461041756349, width: 0.07463377485625412, intervalScore: 0.12854470833945222 },
  { model: "no_change", horizon: 1, span: "2022Q1", band: "online", n: 7378, origins: 18, maePct: 2.3043222589226358, coverage: 0.9053944158308485, width: 0.09837857592295829, intervalScore: 0.13226013590673355 },
  { model: "no_change", horizon: 2, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 3.8771136488562146, coverage: 0.863036303630363, width: 0.17106515092113722, intervalScore: 0.25562994864741506 },
  { model: "no_change", horizon: 2, span: "2022Q1", band: "online", n: 7378, origins: 18, maePct: 3.7163672460087587, coverage: 0.9982380048793711, width: 0.27012238367896046, intervalScore: 0.2703810747612991 },
  { model: "no_change", horizon: 4, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 7.456410514782613, coverage: 0.7843306069737409, width: 0.3401982612296544, intervalScore: 0.6084243231328099 },
  { model: "no_change", horizon: 4, span: "2022Q1", band: "online", n: 7378, origins: 18, maePct: 7.660592997025248, coverage: 0.8462998102466793, width: 0.5644419974772449, intervalScore: 0.8134975359868921 },
  { model: "no_change", horizon: 8, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 15.487573261299548, coverage: 0.6969436074042187, width: 0.4902296833867217, intervalScore: 1.0591657311696205 },
  { model: "no_change", horizon: 8, span: "2022Q1", band: "online", n: 7378, origins: 18, maePct: 18.054345566788314, coverage: 0.6171049064787205, width: 0.7653320018300297, intervalScore: 1.6361268310480597 },
  { model: "ridge", horizon: 1, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 1.5955331279049845, coverage: 0.8670540967140192, width: 0.06744607439251149, intervalScore: 0.10542960739370677 },
  { model: "ridge", horizon: 2, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 2.359108696688855, coverage: 0.8376381116372507, width: 0.1259548858139009, intervalScore: 0.21474543058695364 },
  { model: "ridge", horizon: 4, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 4.6961946142452025, coverage: 0.808437365475678, width: 0.2964412546144206, intervalScore: 0.4949986136314491 },
  { model: "ridge", horizon: 8, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 8.040781266027919, coverage: 0.7264313387860525, width: 0.42327945354442925, intervalScore: 0.8513029498864515 },
  { model: "seqgru", horizon: 1, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 1.7064767382221961, coverage: 0.8653321853924523, width: 0.07191166664761005, intervalScore: 0.11326747470219792 },
  { model: "seqgru", horizon: 1, span: "2022Q1", band: "online", n: 7378, origins: 18, maePct: 1.983366351175894, coverage: 0.9091894822445107, width: 0.09689841961639574, intervalScore: 0.12317859141668915 },
  { model: "seqgru", horizon: 1, span: "2022Q1", band: "static", n: 7378, origins: 18, maePct: 1.983366351175894, coverage: 0.8354567633505015, width: 0.07013961196253235, intervalScore: 0.12157639969121609 },
  { model: "seqgru", horizon: 2, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 2.5487383091987006, coverage: 0.8679150523748027, width: 0.16121189602408614, intervalScore: 0.2291286093437462 },
  { model: "seqgru", horizon: 2, span: "2022Q1", band: "online", n: 7378, origins: 18, maePct: 2.7534914698272592, coverage: 0.9991867714827867, width: 0.25900395843793195, intervalScore: 0.25925086928056285 },
  { model: "seqgru", horizon: 2, span: "2022Q1", band: "static", n: 7378, origins: 18, maePct: 2.7534914698272592, coverage: 0.8997018162103552, width: 0.11774084713715453, intervalScore: 0.1610460872203891 },
  { model: "seqgru", horizon: 4, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 4.226355678234946, coverage: 0.7925814320562491, width: 0.30799884222047286, intervalScore: 0.5286286299231905 },
  { model: "seqgru", horizon: 4, span: "2022Q1", band: "online", n: 7378, origins: 18, maePct: 4.918328396898779, coverage: 0.8850637029005151, width: 0.5251607110870515, intervalScore: 0.6917073204366576 },
  { model: "seqgru", horizon: 4, span: "2022Q1", band: "static", n: 7378, origins: 18, maePct: 4.918328396898779, coverage: 0.844266738953646, width: 0.18369032635827373, intervalScore: 0.29286056272917554 },
  { model: "seqgru", horizon: 8, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 8.20330583055987, coverage: 0.7198306787200459, width: 0.45085531433991743, intervalScore: 0.9408117101966449 },
  { model: "seqgru", horizon: 8, span: "2022Q1", band: "online", n: 7378, origins: 18, maePct: 11.465637659246884, coverage: 0.6457034426673895, width: 0.7242872751798493, intervalScore: 1.4797783268845048 },
  { model: "seqgru", horizon: 8, span: "2022Q1", band: "static", n: 7378, origins: 18, maePct: 11.465637659246884, coverage: 0.5447275684467335, width: 0.1915009006404455, intervalScore: 0.8313823131982292 },
  { model: "windowmlp", horizon: 1, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 1.804911639250952, coverage: 0.8742287272205481, width: 0.07973682788656972, intervalScore: 0.11490495388784218 },
  { model: "windowmlp", horizon: 2, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 2.8176808587511917, coverage: 0.8542832544123977, width: 0.1463605203475973, intervalScore: 0.22454407821742364 },
  { model: "windowmlp", horizon: 4, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 5.177463469509444, coverage: 0.7909312670397475, width: 0.3011360278425355, intervalScore: 0.5289176553708702 },
  { model: "windowmlp", horizon: 8, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 10.79140583957128, coverage: 0.6886210360166451, width: 0.6588863870504235, intervalScore: 1.2094120259537093 },
];

// the shipped model's and no change's record fed the index as fhfa prints it
// today, which says how much the revisions were worth
export const WALKFORWARD_LATEST: WalkRow[] = [
  { model: "no_change", horizon: 1, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 2.2527086060019865, coverage: 0.8532070598364184, width: 0.07539089625985045, intervalScore: 0.12840186557967312 },
  { model: "no_change", horizon: 2, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 3.8771136488562146, coverage: 0.8621036016645143, width: 0.1756321560395729, intervalScore: 0.2602454086491187 },
  { model: "no_change", horizon: 4, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 7.456410514782613, coverage: 0.7841871143636103, width: 0.34214528630850344, intervalScore: 0.609799936347401 },
  { model: "no_change", horizon: 8, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 15.487573261299548, coverage: 0.6960826517434352, width: 0.49111283344056567, intervalScore: 1.0639303987344007 },
  { model: "seqgru", horizon: 1, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 1.7001114248463594, coverage: 0.8659779021380399, width: 0.0719073331283865, intervalScore: 0.11265958863239953 },
  { model: "seqgru", horizon: 2, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 2.5220228967980534, coverage: 0.8683455302051944, width: 0.16026282349872756, intervalScore: 0.22776917704421779 },
  { model: "seqgru", horizon: 4, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 4.167458636174415, coverage: 0.7953077916487301, width: 0.3080282838877494, intervalScore: 0.5350268134571632 },
  { model: "seqgru", horizon: 8, span: "2018Q1", band: "online", n: 13938, origins: 34, maePct: 8.263144247307656, coverage: 0.7205481417706988, width: 0.4570907675029435, intervalScore: 0.9652872096034425 },
];

// the shipped model's online band settings for each horizon, chosen on the
// outcomes before the record. a window of 0 is every outcome realized so far
export const WALKFORWARD_BANDS: WalkBand[] = [
  { model: "seqgru", horizon: 1, gamma: 0.05, window: 40, scaled: true },
  { model: "seqgru", horizon: 2, gamma: 0.05, window: 16, scaled: true },
  { model: "seqgru", horizon: 4, gamma: 0.05, window: 16, scaled: true },
  { model: "seqgru", horizon: 8, gamma: 0.05, window: 16, scaled: true },
];

// the shipped model against every other one over the record, and against no
// change over 2022 onward, a paired test per span and horizon. difference is
// the shipped model's mean error less the other's, in points, so a negative
// one has it closer
export const WALKFORWARD_PAIRED: WalkPairedRow[] = [
  { span: "2018Q1", against: "ensemble", horizon: 1, origins: 34, difference: 0.08790206374109598, pValue: 0.020591865891135028 },
  { span: "2018Q1", against: "ensemble", horizon: 2, origins: 34, difference: 0.14488523542400578, pValue: 0.15187246206304578 },
  { span: "2018Q1", against: "ensemble", horizon: 4, origins: 34, difference: -0.1744658254456234, pValue: 0.4661179155416591 },
  { span: "2018Q1", against: "ensemble", horizon: 8, origins: 34, difference: 0.11045653736168812, pValue: 0.3001738385416842 },
  { span: "2018Q1", against: "gbm", horizon: 1, origins: 34, difference: 0.10797373235227038, pValue: 0.2453234390833523 },
  { span: "2018Q1", against: "gbm", horizon: 2, origins: 34, difference: 0.19270391866813463, pValue: 0.40341167181623727 },
  { span: "2018Q1", against: "gbm", horizon: 4, origins: 34, difference: 0.034989793644479496, pValue: 0.9298679909749069 },
  { span: "2018Q1", against: "gbm", horizon: 8, origins: 34, difference: 0.08826754802015355, pValue: 0.9187352900338641 },
  { span: "2018Q1", against: "metro_mean", horizon: 1, origins: 34, difference: -0.11368607514968705, pValue: 0.14019359239224985 },
  { span: "2018Q1", against: "metro_mean", horizon: 2, origins: 34, difference: -0.25713481659163706, pValue: 0.28155974250786675 },
  { span: "2018Q1", against: "metro_mean", horizon: 4, origins: 34, difference: -0.4740714686172358, pValue: 0.343687866268544 },
  { span: "2018Q1", against: "metro_mean", horizon: 8, origins: 34, difference: -1.0990544961433357, pValue: 0.40676765587113073 },
  { span: "2018Q1", against: "momentum", horizon: 1, origins: 34, difference: -0.05519523898077692, pValue: 0.49639573537741327 },
  { span: "2018Q1", against: "momentum", horizon: 2, origins: 34, difference: -0.13242096388888444, pValue: 0.5238072573267365 },
  { span: "2018Q1", against: "momentum", horizon: 4, origins: 34, difference: -0.8813846414434899, pValue: 0.13780574463621129 },
  { span: "2018Q1", against: "momentum", horizon: 8, origins: 34, difference: -3.256348406382171, pValue: 0.10979903115238179 },
  { span: "2018Q1", against: "no_change", horizon: 1, origins: 34, difference: -0.5459886548554891, pValue: 0.0002859532360866611 },
  { span: "2018Q1", against: "no_change", horizon: 2, origins: 34, difference: -1.3280888784488574, pValue: 0.0012041436173993085 },
  { span: "2018Q1", against: "no_change", horizon: 4, origins: 34, difference: -3.2301629168365023, pValue: 0.00005087926986421008 },
  { span: "2018Q1", against: "no_change", horizon: 8, origins: 34, difference: -7.284298517293336, pValue: 0.00023042716585197086 },
  { span: "2018Q1", against: "ridge", horizon: 1, origins: 34, difference: 0.11081801606477529, pValue: 0.11467794138953163 },
  { span: "2018Q1", against: "ridge", horizon: 2, origins: 34, difference: 0.18941228008895525, pValue: 0.2983158692112646 },
  { span: "2018Q1", against: "ridge", horizon: 4, origins: 34, difference: -0.46983169674159514, pValue: 0.3481999378337327 },
  { span: "2018Q1", against: "ridge", horizon: 8, origins: 34, difference: 0.16275952751546843, pValue: 0.4581386241934381 },
  { span: "2018Q1", against: "windowmlp", horizon: 1, origins: 34, difference: -0.09838475124159086, pValue: 0.024477054220876725 },
  { span: "2018Q1", against: "windowmlp", horizon: 2, origins: 34, difference: -0.2688298874382391, pValue: 0.03819514799140736 },
  { span: "2018Q1", against: "windowmlp", horizon: 4, origins: 34, difference: -0.9508383491033858, pValue: 0.021427689912424015 },
  { span: "2018Q1", against: "windowmlp", horizon: 8, origins: 34, difference: -2.5879501744083657, pValue: 0.03607999520819973 },
  { span: "2022Q1", against: "no_change", horizon: 1, origins: 18, difference: -0.3205575559520683, pValue: 0.15953424312108055 },
  { span: "2022Q1", against: "no_change", horizon: 2, origins: 18, difference: -0.9624337341595864, pValue: 0.15539270669058686 },
  { span: "2022Q1", against: "no_change", horizon: 4, origins: 18, difference: -2.742600944259156, pValue: 0.0478306122208408 },
  { span: "2022Q1", against: "no_change", horizon: 8, origins: 18, difference: -6.588955125103004, pValue: 0.11280608210450384 },
];

// what the coverage figure shows, as loop.panel wrote it into
// ml/results/panel_manifest.json
export const PANEL_COVERAGE: PanelCoverage | null = {"fitEnd":"2014Q4","first":1975,"last":2026,"series":[{"label":"hpi","first":1975,"emptyBeforeFit":false},{"label":"expanded hpi","first":1991,"emptyBeforeFit":false},{"label":"index error","first":1991,"emptyBeforeFit":false},{"label":"national macro","first":1975,"emptyBeforeFit":false},{"label":"unemp","first":1990,"emptyBeforeFit":false},{"label":"mortgage","first":1975,"emptyBeforeFit":false},{"label":"zhvi","first":2000,"emptyBeforeFit":false},{"label":"zori","first":2015,"emptyBeforeFit":true},{"label":"permits","first":2015,"emptyBeforeFit":true},{"label":"population","first":2012,"emptyBeforeFit":false},{"label":"income","first":2016,"emptyBeforeFit":true},{"label":"listings","first":2019,"emptyBeforeFit":true},{"label":"inventory","first":2020,"emptyBeforeFit":true}],"features":11,"unseen":["permits_per_1000","income_growth"]};
