// generated by scripts/model-assets.mjs from ml/results/backtest. do not
// edit by hand: npm run build rewrites it from the csvs the backtest wrote,
// so a retrain that changes the numbers changes this file in the same commit.
import type { BacktestRow, RawBand, TrainingFacts, ForecastFacts, PanelFacts, PanelCoverage, PairedRow, AdmissionRow } from "./model";

// the test block only, outcomes realized 2022Q1 or later, scored once
export const BACKTEST: BacktestRow[] = [
  { model: "gbm", horizon: 1, maePct: 1.9798129593044367, coverage: 0.7934399566278124, width: 0.05924516555967928, n: 7378 },
  { model: "gbm", horizon: 2, maePct: 2.8794963362233457, coverage: 0.8319327731092437, width: 0.0926025451780958, n: 7378 },
  { model: "gbm", horizon: 4, maePct: 5.045249286377029, coverage: 0.8605313092979127, width: 0.157816948419914, n: 7378 },
  { model: "gbm", horizon: 8, maePct: 13.066639676154786, coverage: 0.698292220113852, width: 0.23285463538902113, n: 7378 },
  { model: "metro_mean", horizon: 1, maePct: 2.02464502451641, coverage: 0.877744646245595, width: 0.08426490566460203, n: 7378 },
  { model: "metro_mean", horizon: 2, maePct: 2.9037272617707184, coverage: 0.917863919761453, width: 0.1491336260948901, n: 7378 },
  { model: "metro_mean", horizon: 4, maePct: 5.130428219508361, coverage: 0.8675792897804283, width: 0.23593019348690983, n: 7378 },
  { model: "metro_mean", horizon: 8, maePct: 11.820198549976126, coverage: 0.6856871780970453, width: 0.3240752720214804, n: 7378 },
  { model: "momentum", horizon: 1, maePct: 2.101910686976233, coverage: 0.7558959067497967, width: 0.05891220299929865, n: 7378 },
  { model: "momentum", horizon: 2, maePct: 2.943806163246689, coverage: 0.8347790729194904, width: 0.10075445477300624, n: 7378 },
  { model: "momentum", horizon: 4, maePct: 5.885882509513564, coverage: 0.8130929791271347, width: 0.18218520759462437, n: 7378 },
  { model: "momentum", horizon: 8, maePct: 15.55812160781137, coverage: 0.5399837354296557, width: 0.23927358771520793, n: 7378 },
  { model: "no_change", horizon: 1, maePct: 2.3043222589226358, coverage: 0.8671726755218216, width: 0.07896099305750558, n: 7378 },
  { model: "no_change", horizon: 2, maePct: 3.716367246008759, coverage: 0.9120357820547574, width: 0.13585860115768428, n: 7378 },
  { model: "no_change", horizon: 4, maePct: 7.660592997025248, coverage: 0.8628354567633505, width: 0.20120337195961893, n: 7378 },
  { model: "no_change", horizon: 8, maePct: 18.05434556678832, coverage: 0.6779615071835186, width: 0.2509667382984162, n: 7378 },
  { model: "ridge", horizon: 1, maePct: 1.8753931268975044, coverage: 0.813228517213337, width: 0.06165737468019703, n: 7378 },
  { model: "ridge", horizon: 2, maePct: 2.539255509351907, coverage: 0.8971265925725129, width: 0.1068884751140937, n: 7378 },
  { model: "ridge", horizon: 4, maePct: 4.501441164773867, coverage: 0.8621577663323394, width: 0.1702529871414318, n: 7378 },
  { model: "ridge", horizon: 8, maePct: 10.543415812677054, coverage: 0.6321496340471673, width: 0.19768877169679389, n: 7378 },
  { model: "seqgru", horizon: 1, maePct: 1.9602530573706352, coverage: 0.8297641637300082, width: 0.06799714248742293, n: 7378 },
  { model: "seqgru", horizon: 2, maePct: 2.671279453262647, coverage: 0.9049878015722418, width: 0.11470565617899442, n: 7378 },
  { model: "seqgru", horizon: 4, maePct: 4.534634901141644, coverage: 0.8662239089184061, width: 0.18241369790897707, n: 7378 },
  { model: "seqgru", horizon: 8, maePct: 10.747277911560744, coverage: 0.6420439143399295, width: 0.21333480981100572, n: 7378 },
  { model: "windowmlp", horizon: 1, maePct: 2.249289754468098, coverage: 0.8549742477636216, width: 0.08120229890656891, n: 7378 },
  { model: "windowmlp", horizon: 2, maePct: 3.4767002464936563, coverage: 0.9430740037950665, width: 0.15006127367356595, n: 7378 },
  { model: "windowmlp", horizon: 4, maePct: 7.108772560744736, coverage: 0.9174573055028463, width: 0.26795602022342263, n: 7378 },
  { model: "windowmlp", horizon: 8, maePct: 16.207366610656535, coverage: 0.6949037679587964, width: 0.3811384458599754, n: 7378 },
];

// what the shipped model reads: a sequence over the window, a value at the
// origin, and the columns the panel carries that no model touches
export const INPUTS = { sequence: 7, annual: 4, context: 10 };

// the shipped model's raw 10 to 90 band on the test block, before the margin
export const RAW_BAND: RawBand[] = [
  { horizon: 1, coverage: 0.5898617511520737 },
  { horizon: 2, coverage: 0.623475196530225 },
  { horizon: 4, coverage: 0.669693683925183 },
  { horizon: 8, coverage: 0.580238547031716 },
];

// the two networks' training histories: where validation loss was lowest
export const TRAINING: TrainingFacts[] = [
  { model: "windowmlp", stop: 1, last: 6, flatFrom: null, trainFalls: true },
  { model: "seqgru", stop: 8, last: 13, flatFrom: 3, trainFalls: false },
];

// the shipped forecast as ml/results/forecast/forecasts.csv has it
export const FORECAST: ForecastFacts = {"origin":"2026Q2","end":"2028Q2","far":8,"count":410,"p10":1.6459839866196502,"median":3.7011664794451615,"p90":5.707723263840914,"lowest":-0.7993253227299824,"highest":8.637333739350828,"falling":5,"peak":{"from":2.6607830000329815,"to":2.9753383021023416,"count":35},"fans":[{"cbsa":"16984","median":13.229238317728086,"lo":-5.623649770569039,"hi":39.00626698772201},{"cbsa":"12420","median":1.5250142017174229,"lo":-15.421607013572125,"hi":22.906463020347047}]};

// the panel the model is fitted on, from ml/results/panel_manifest.json
export const PANEL: PanelFacts = {"rows":71072,"metros":410,"first":"1975Q1","last":"2026Q2"};

// the calibration samples the shipped model's band was set on, at every horizon
export const CALIBRATION_N: number | null = 6560;

// the shipped model against every other scored model, a paired test per
// horizon over the test block's origins. difference is the shipped model's
// mean error less the other's, in points, so a negative one has it closer
export const PAIRED: PairedRow[] = [
  { against: "gbm", horizon: 1, origins: 18, difference: -0.019760477554185127, pValue: 0.9151250811330677 },
  { against: "gbm", horizon: 2, origins: 18, difference: -0.2086140030776883, pValue: 0.6274597364179442 },
  { against: "gbm", horizon: 4, origins: 18, difference: -0.5108220063824063, pValue: 0.6779086903501467 },
  { against: "gbm", horizon: 8, origins: 18, difference: -2.3186103619586143, pValue: 0.5956711041964486 },
  { against: "metro_mean", horizon: 1, origins: 18, difference: -0.06420931583565381, pValue: 0.5482519462550728 },
  { against: "metro_mean", horizon: 2, origins: 18, difference: -0.23214731623783058, pValue: 0.5392168647937307 },
  { against: "metro_mean", horizon: 4, origins: 18, difference: -0.5960359842943271, pValue: 0.4833673029252545 },
  { against: "metro_mean", horizon: 8, origins: 18, difference: -1.0728863798658885, pValue: 0.5551091023880084 },
  { against: "momentum", horizon: 1, origins: 18, difference: -0.14185893843950476, pValue: 0.35213100722896923 },
  { against: "momentum", horizon: 2, origins: 18, difference: -0.273058036739805, pValue: 0.4898983259588031 },
  { against: "momentum", horizon: 4, origins: 18, difference: -1.351643433837311, pValue: 0.2912320344352449 },
  { against: "momentum", horizon: 8, origins: 18, difference: -4.810065191643104, pValue: 0.2986589303911128 },
  { against: "no_change", horizon: 1, origins: 18, difference: -0.34373340871529146, pValue: 0.0914129852255687 },
  { against: "no_change", horizon: 2, origins: 18, difference: -1.0447280813799926, pValue: 0.09457654350270026 },
  { against: "no_change", horizon: 4, origins: 18, difference: -3.1263305572179108, pValue: 0.01705463585015081 },
  { against: "no_change", horizon: 8, origins: 18, difference: -7.307164519218375, pValue: 0.018389150767575323 },
  { against: "ridge", horizon: 1, origins: 18, difference: 0.08462846747669472, pValue: 0.3973231932773714 },
  { against: "ridge", horizon: 2, origins: 18, difference: 0.1319453661081431, pValue: 0.13250946376373357 },
  { against: "ridge", horizon: 4, origins: 18, difference: 0.03317667665589324, pValue: 0.9433425127266017 },
  { against: "ridge", horizon: 8, origins: 18, difference: 0.20418220753878916, pValue: 0.7171296654783378 },
  { against: "windowmlp", horizon: 1, origins: 18, difference: -0.2888573889337491, pValue: 0.007513137752657504 },
  { against: "windowmlp", horizon: 2, origins: 18, difference: -0.8050191880462567, pValue: 0.018546047161211887 },
  { against: "windowmlp", horizon: 4, origins: 18, difference: -2.5735086288376636, pValue: 0.06003899936109775 },
  { against: "windowmlp", horizon: 8, origins: 18, difference: -5.459755761919118, pValue: 0.14432652414567565 },
];

// the admission run's validation loss by arm and seed, as ml/admit.py wrote it
export const ADMISSION: AdmissionRow[] = [
  { arm: "nine, what the shipped gate could see", seed: 20260915, loss: 0.01337 },
  { arm: "nine, what the shipped gate could see", seed: 20260916, loss: 0.013552 },
  { arm: "nine, what the shipped gate could see", seed: 20260917, loss: 0.013433 },
  { arm: "nine, what the shipped gate could see", seed: 20260918, loss: 0.013404 },
  { arm: "nine, what the shipped gate could see", seed: 20260919, loss: 0.013502 },
  { arm: "thirteen, plus rents listings permits income", seed: 20260915, loss: 0.013174 },
  { arm: "thirteen, plus rents listings permits income", seed: 20260916, loss: 0.013355 },
  { arm: "thirteen, plus rents listings permits income", seed: 20260917, loss: 0.013255 },
  { arm: "thirteen, plus rents listings permits income", seed: 20260918, loss: 0.013204 },
  { arm: "thirteen, plus rents listings permits income", seed: 20260919, loss: 0.013261 },
  { arm: "fourteen, the set shipped before 2026-09-18", seed: 20260915, loss: 0.013156 },
  { arm: "fourteen, the set shipped before 2026-09-18", seed: 20260916, loss: 0.013183 },
  { arm: "fourteen, the set shipped before 2026-09-18", seed: 20260917, loss: 0.013255 },
  { arm: "fourteen, the set shipped before 2026-09-18", seed: 20260918, loss: 0.0132 },
  { arm: "fourteen, the set shipped before 2026-09-18", seed: 20260919, loss: 0.013187 },
  { arm: "eleven, without zori and listings", seed: 20260915, loss: 0.013195 },
  { arm: "eleven, without zori and listings", seed: 20260916, loss: 0.01345 },
  { arm: "eleven, without zori and listings", seed: 20260917, loss: 0.013297 },
  { arm: "eleven, without zori and listings", seed: 20260918, loss: 0.013261 },
  { arm: "eleven, without zori and listings", seed: 20260919, loss: 0.013183 },
  { arm: "eleven, without permits and income", seed: 20260915, loss: 0.013274 },
  { arm: "eleven, without permits and income", seed: 20260916, loss: 0.013307 },
  { arm: "eleven, without permits and income", seed: 20260917, loss: 0.013364 },
  { arm: "eleven, without permits and income", seed: 20260918, loss: 0.013344 },
  { arm: "eleven, without permits and income", seed: 20260919, loss: 0.013418 },
];

// what the coverage figure shows, as loop.panel wrote it into
// ml/results/panel_manifest.json
export const PANEL_COVERAGE: PanelCoverage | null = {"fitEnd":"2014Q4","first":1975,"last":2026,"series":[{"label":"hpi","first":1975,"emptyBeforeFit":false},{"label":"expanded hpi","first":1991,"emptyBeforeFit":false},{"label":"index error","first":1991,"emptyBeforeFit":false},{"label":"national macro","first":1975,"emptyBeforeFit":false},{"label":"unemp","first":1990,"emptyBeforeFit":false},{"label":"mortgage","first":1975,"emptyBeforeFit":false},{"label":"zhvi","first":2000,"emptyBeforeFit":false},{"label":"zori","first":2015,"emptyBeforeFit":true},{"label":"permits","first":2015,"emptyBeforeFit":true},{"label":"population","first":2012,"emptyBeforeFit":false},{"label":"income","first":2016,"emptyBeforeFit":true},{"label":"listings","first":2019,"emptyBeforeFit":true},{"label":"inventory","first":2020,"emptyBeforeFit":true}],"features":11,"unseen":["permits_per_1000","income_growth"]};
