import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { FIGURES, leaderboard, parseBacktest, pngSize, renderModule, testRows } from "./model-assets.mjs";
import { FIGURES as PAGE_FIGURES, FIGURE_FILES, FIGURE_IDS } from "../src/lib/modelFigures.ts";

const CSV = [
  "model,horizon,block,n,mae,coverage,width,mae_pct",
  "ridge,1,train,56663,0.0144,0.85,0.0517,1.4624848",
  "ridge,1,cal,6560,0.0109,0.90,0.0517,1.1239",
  "ridge,1,test,7378,0.0178,0.7599620,0.0517267,1.818406125",
  "ridge,8,test,7378,0.0873,0.6427216,0.1960825,10.40866653",
].join("\n");

const FIGURE_DIR = new URL("../../ml/results/figures/", import.meta.url);

describe("reading a backtest csv", () => {
  it("keeps a row per line and a column per header", () => {
    const rows = parseBacktest(CSV);
    expect(rows).toHaveLength(4);
    expect(rows[0].model).toBe("ridge");
    expect(rows[0].block).toBe("train");
  });

  it("has nothing to say about an empty file or a header on its own", () => {
    expect(parseBacktest("")).toEqual([]);
    expect(parseBacktest("model,horizon,block\n")).toEqual([]);
  });

  // train and calibration are the model's own working, and quoting either as
  // a result would be quoting a score the model was allowed to see
  it("publishes the test block and nothing else", () => {
    expect(testRows(CSV).map((row) => row.horizon)).toEqual([1, 8]);
  });

  it("carries the error, the coverage and the band width for each horizon", () => {
    expect(testRows(CSV)[0]).toEqual({
      model: "ridge", horizon: 1, n: 7378, maePct: 1.8184, coverage: 0.76, width: 0.0517,
    });
  });

  // four places is finer than the page prints and keeps a retrain's diff to
  // the numbers that actually moved
  it("rounds to four places", () => {
    expect(testRows(CSV)[1].maePct).toBe(10.4087);
  });

  it("sorts by model and horizon so a rebuild does not churn the file", () => {
    const other = CSV.replace(/ridge/g, "gbm");
    expect(leaderboard([CSV, other]).map((row) => `${row.model}${row.horizon}`))
      .toEqual(["gbm1", "gbm8", "ridge1", "ridge8"]);
  });
});

describe("the module the build writes", () => {
  const module = renderModule(leaderboard([CSV]));

  it("says it is generated and where it came from", () => {
    expect(module).toContain("generated by scripts/model-assets.mjs");
    expect(module).toContain("ml/results/backtest");
  });

  it("types its rows against the page's own row type", () => {
    expect(module).toContain('import type { BacktestRow } from "./model";');
    expect(module).toContain("export const BACKTEST: BacktestRow[] = [");
  });

  it("writes one literal per row", () => {
    expect(module).toContain('{ model: "ridge", horizon: 1, maePct: 1.8184, coverage: 0.76, width: 0.0517, n: 7378 },');
    expect(module.trimEnd().split("\n").filter((line) => line.startsWith("  { model:"))).toHaveLength(2);
  });
});

describe("the figures the build copies", () => {
  // the page renders what modelFigures names and the build copies what this
  // script names. if the two drift, a reader gets a caption and no figure
  it("are exactly the figures the page names", () => {
    expect([...FIGURES].sort()).toEqual([...FIGURE_FILES].sort());
  });

  it("are a subset of what the ml folder renders, not all of it", () => {
    expect(FIGURES.length).toBeLessThan(13);
    expect(FIGURES.length).toBeGreaterThan(4);
  });

  it("reads a png's real size out of its header", () => {
    const first = new URL(FIGURES[0], FIGURE_DIR);
    if (!existsSync(first)) return;
    const size = pngSize(readFileSync(first));
    expect(size?.width).toBeGreaterThan(400);
    expect(size?.height).toBeGreaterThan(400);
  });

  it("has nothing to say about a buffer that is not a png", () => {
    expect(pngSize(Buffer.from("not a png"))).toBeNull();
  });

  // the page declares a width and height so the prose under a figure does not
  // jump when the png lands. a re-render at another size would make those
  // attributes a lie, and this is where that shows up
  it("are the size the page says they are", () => {
    for (const id of FIGURE_IDS) {
      const figure = PAGE_FIGURES[id];
      const path = new URL(figure.file, FIGURE_DIR);
      if (!existsSync(path)) continue;
      expect(pngSize(readFileSync(path)), figure.file).toEqual({ width: figure.width, height: figure.height });
    }
  });
});
