// puts the model page's two build inputs in place: the figures the ml folder
// renders, and the leaderboard it backtested. both live under ml/results,
// which the deployed site cannot reach, so the figures are copied into
// public/ and the numbers are compiled into a tracked module.
//
// the numbers are generated rather than typed in because a retrain rewrites
// those csvs, and a page quoting them by hand would go on publishing the old
// ones with nobody the wiser. the figures are copied rather than committed
// twice because they are 2.1 MB that git already carries once.
//
//   node scripts/model-assets.mjs      runs as prebuild, before tsc and vite
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const WEB = new URL("../", import.meta.url);
const ML = new URL("../ml/results/", WEB);
const OUT_FIGURES = new URL("public/figures/", WEB);
const OUT_MODULE = new URL("src/lib/modelNumbers.ts", WEB);

// the backtest files that carry a test block. one row per model, horizon and
// block; everything else in ml/results/backtest is margins or epoch history
export const BACKTEST_FILES = ["baselines.csv", "seqgru.csv", "windowmlp.csv"];

// the seven figures the page shows. the other six in ml/results/figures are
// panel description or a baseline-only view of a chart that is already here,
// and copying them would ship megabytes nothing on the page asks for
export const FIGURES = [
  "01_coverage.png",
  "05_backtest_design.png",
  "09_training_curves.png",
  "10_quantile_calibration.png",
  "11_forecast_fans.png",
  "12_model_comparison.png",
  "13_forecast_distribution.png",
];

// the columns the page reads. the csvs carry pinball losses and raw coverage
// too, which belong to the ml folder's own write-up rather than to this page
const KEEP = { mae_pct: "maePct", coverage: "coverage", width: "width" };

// these files are written by one pandas to_csv with plain numeric columns, so
// a split on commas is the whole parser. a quoted field would mean the schema
// changed, and that is a build failure worth having
export function parseBacktest(text) {
  const lines = String(text).trim().split(/\r?\n/).filter((line) => line.length > 0);
  if (lines.length < 2) return [];
  const head = lines[0].split(",");
  return lines.slice(1).map((line) => {
    const cells = line.split(",");
    const row = {};
    head.forEach((name, i) => { row[name] = cells[i]; });
    return row;
  });
}

// one published row per model and horizon: the test block, which is scored
// once and is the only block this page quotes
export function testRows(text) {
  const out = [];
  for (const row of parseBacktest(text)) {
    if (row.block !== "test") continue;
    const cell = { model: row.model, horizon: Number(row.horizon), n: Number(row.n) };
    for (const [csv, key] of Object.entries(KEEP)) cell[key] = round(Number(row[csv]));
    if (!row.model || !Number.isFinite(cell.horizon)) continue;
    out.push(cell);
  }
  return out;
}

// four places is finer than anything the page prints and keeps a retrain's
// diff readable
function round(value) {
  return Number.isFinite(value) ? Number(value.toFixed(4)) : null;
}

export function leaderboard(texts) {
  const rows = texts.flatMap(testRows);
  return rows.sort((a, b) => a.model.localeCompare(b.model) || a.horizon - b.horizon);
}

export function renderModule(rows) {
  const body = rows
    .map((r) => `  { model: "${r.model}", horizon: ${r.horizon}, maePct: ${r.maePct}, `
      + `coverage: ${r.coverage}, width: ${r.width}, n: ${r.n} },`)
    .join("\n");
  return [
    "// generated by scripts/model-assets.mjs from ml/results/backtest. do not",
    "// edit by hand: npm run build rewrites it from the csvs the backtest wrote,",
    "// so a retrain that changes the numbers changes this file in the same commit.",
    "import type { BacktestRow } from \"./model\";",
    "",
    "// the test block only, outcomes realized 2022Q1 or later, scored once",
    "export const BACKTEST: BacktestRow[] = [",
    body,
    "];",
    "",
  ].join("\n");
}

// width and height out of a png IHDR, so the page can declare the size a
// figure really is instead of a number somebody remembered
export function pngSize(buffer) {
  if (buffer.length < 24 || buffer.toString("ascii", 12, 16) !== "IHDR") return null;
  return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
}

function copyFigures() {
  mkdirSync(fileURLToPath(OUT_FIGURES), { recursive: true });
  let copied = 0;
  const missing = [];
  for (const name of FIGURES) {
    const from = new URL(`figures/${name}`, ML);
    if (!existsSync(from)) { missing.push(name); continue; }
    copyFileSync(from, new URL(name, OUT_FIGURES));
    copied += 1;
  }
  return { copied, missing };
}

function writeNumbers() {
  const texts = [];
  for (const name of BACKTEST_FILES) {
    const path = new URL(`backtest/${name}`, ML);
    if (existsSync(path)) texts.push(readFileSync(path, "utf8"));
  }
  if (texts.length === 0) return { rows: 0, changed: false };
  const rows = leaderboard(texts);
  const next = renderModule(rows);
  const current = existsSync(OUT_MODULE) ? readFileSync(OUT_MODULE, "utf8") : "";
  // only touching the file when the numbers moved keeps the dev server from
  // reloading on every build
  if (next !== current) writeFileSync(OUT_MODULE, next);
  return { rows: rows.length, changed: next !== current };
}

function main() {
  if (!existsSync(ML)) {
    // the page degrades to captions without figures rather than failing a
    // build on a checkout that has no ml folder
    console.warn("[model-assets] no ml/results here, leaving the page's figures and numbers as they are");
    return;
  }
  const figures = copyFigures();
  const numbers = writeNumbers();
  console.log(`[model-assets] ${figures.copied} figures into public/figures, `
    + `${numbers.rows} backtest rows ${numbers.changed ? "rewritten" : "unchanged"}`);
  if (figures.missing.length > 0) {
    console.warn(`[model-assets] not rendered yet, the page will skip them: ${figures.missing.join(", ")}`);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) main();
